Number of 'yes' images: 154
Number of 'no' images: 91

Sequential execution time: 9717.20770573616 seconds
Processed images saved to yes_full_processed_images.pkl
Processed images saved to no_full_processed_images.pkl

Pooling execution time: 1908.0378203392029 seconds
**************** pooling process_image Performance Analysis ****************
Speedup             5.092775207154268
Efficiency          0.8487958678590446
Amdahl’s speedup    6.002286155388279
Gustafson’s speedup 6.0003808807726084

Hessian execution time: 6066.10 seconds (combined threading and pooling)
**************** hessian process_image (combined threading + pooling) Performance Analysis ****************
Speedup             1.601887807797245
Efficiency          0.26698130129954084
Amdahl’s speedup    6.00071886483966
Gustafson’s speedup 6.0001197964537

Processed images loaded from yes_full_processed_images.pkl
Processed images loaded from no_full_processed_images.pkl

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 10.34it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:03<00:00,  6.61it/s]
Exception in thread Thread-43 (process_single_image):█████████████████████████████████████████████████████████████████████████████████████████████████████████████▋        | 19/20 [00:02<00:00,  5.73it/s]
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
Exception in thread Thread-25 (process_single_image):
Traceback (most recent call last):
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
Exception in thread Thread-39 (process_single_image):
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self._launch(process_obj)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
    self._launch(process_obj)
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
Exception in thread Thread-34 (process_single_image):
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
Exception in thread Thread-36 (process_single_image):
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
    self._launch(process_obj)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
Exception in thread Thread-12 (process_single_image):
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    return Popen(process_obj)
Exception in thread Thread-24 (process_single_image):
           ^^^^^^^^^^^^^^^^^^
Exception in thread Thread-48 (process_single_image):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
Exception in thread Thread-50 (process_single_image):
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
Exception in thread Thread-52 (process_single_image):
    self.run()
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self.run()
Traceback (most recent call last):
    self._launch(process_obj)
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
Exception in thread Thread-29 (process_single_image):
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.pid = os.fork()
Traceback (most recent call last):
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
Exception in thread Thread-30 (process_single_image):
    self._target(*self._args, **self._kwargs)
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    self.run()
Traceback (most recent call last):
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    self._target(*self._args, **self._kwargs)
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
               ^^^^^^^^^
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    self.run()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._target(*self._args, **self._kwargs)
    with Pool(processes=None) as pool: 
OSError: [Errno 12] Cannot allocate memory
    with Pool(processes=None) as pool: 
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
  File "/home/student/anaconda3/lib/python3.12/threading.py", line 1012, in run
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
         ^^^^^^^^^^^^^^^^^^^^
    with Pool(processes=None) as pool: 
    with Pool(processes=None) as pool: 
         ^^^^^^^^^^^^^^^^^^^^
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild,
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    return Pool(processes, initializer, initargs, maxtasksperchild,
    self._target(*self._args, **self._kwargs)
    return Pool(processes, initializer, initargs, maxtasksperchild,
    with Pool(processes=None) as pool: 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    self._repopulate_pool()
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 27, in process_single_image
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._repopulate_pool()
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
    'Hessian': compute_hessian(image, sigmas=range(1, 100, 1)),  # Parallelized Hessian
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
  File "/home/student/Parallel-and-Distributed-Computing/src/pt2_process_image_hessian.py", line 16, in compute_hessian
    self._popen = self._Popen(self)
    return self._repopulate_pool_static(self._ctx, self.Process,
    return self._repopulate_pool_static(self._ctx, self.Process,
    return Pool(processes, initializer, initargs, maxtasksperchild,
                  ^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    with Pool(processes=None) as pool: 
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    w.start()
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 119, in Pool
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    return Popen(process_obj)
    return Pool(processes, initializer, initargs, maxtasksperchild,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 215, in __init__
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    self._repopulate_pool()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 306, in _repopulate_pool
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    return self._repopulate_pool_static(self._ctx, self.Process,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 329, in _repopulate_pool_static
    w.start()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
    w.start()
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    self._popen = self._Popen(self)
    self._launch(process_obj)
                  ^^^^^^^^^^^^^^^^^
    return Popen(process_obj)
    return Popen(process_obj)
                  ^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 121, in start
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
    self.pid = os.fork()
    return Popen(process_obj)
    return Popen(process_obj)
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/context.py", line 282, in _Popen
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
           ^^^^^^^^^^^^^^^^^^
    return Popen(process_obj)
               ^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
OSError: [Errno 12] Cannot allocate memory
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
           ^^^^^^^^^^^^^^^^^^
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
    self._launch(process_obj)
    self._launch(process_obj)
    self.pid = os.fork()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
               ^^^^^^^^^
    self._launch(process_obj)
    self.pid = os.fork()
               ^^^^^^^^^
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
OSError: [Errno 12] Cannot allocate memory
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/popen_fork.py", line 66, in _launch
               ^^^^^^^^^
    self.pid = os.fork()
    self.pid = os.fork()
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
               ^^^^^^^^^
OSError: [Errno 12] Cannot allocate memory
OSError: [Errno 12] Cannot allocate memory
Hessian execution time: 6066.10 seconds (combined threading and pooling)
**************** hessian process_image (combined threading + pooling) Performance Analysis ****************
Speedup             1.601887807797245
Efficiency          0.26698130129954084
Amdahl’s speedup    6.00071886483966
Gustafson’s speedup 6.0001197964537

Processed images loaded from yes_full_processed_images.pkl
Processed images loaded from no_full_processed_images.pkl
Process ForkPoolWorker-231:
Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/queues.py", line 399, in put
    self._writer.send_bytes(obj)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/connection.py", line 420, in _send_bytes
    self._send(header)
  File "/home/student/anaconda3/lib/python3.12/multiprocessing/connection.py", line 384, in _send
    n = write(self._handle, buf)
        ^^^^^^^^^^^^^^^^^^^^^^^^
BrokenPipeError: [Errno 32] Broken pipe